version: "3"

services:
  nginx-dga:
    image: paiboon15721/nginx-dga
    restart: unless-stopped
    ports:
      - "80:80"

  nodejs-dga:
    image: paiboon15721/nodejs-dga
    restart: unless-stopped
    env_file:
      - ./nodejs/.env
    ports:
      - "3000:3000"