version: "3"

services:
  dga-nginx:
    image: paiboon15721/dga-nginx
    restart: unless-stopped
    ports:
      - "80:80"

  dga-nodejs:
    image: paiboon15721/dga-nodejs
    restart: unless-stopped
    env_file:
      - ./nodejs/.env
    ports:
      - "3000:3000"