version: "3"

services: 
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./nodejs/.env

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    
  rabbitmq:
    image: rabbitmq:management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"